Ignore missing fields when deserializing
AdrianStrugala/AvroConvert pull request #40
Opened 2021-06-07 06:01 UTC by robertcoltheart

This use case for this is when the producer has added a field (and the schema has been updated in the Schema Registry), but consumers are still using classes that don't yet have the field.

This mimics the Avro deserializer, which always looks up the schema by it's `id` in the Schema Registry and then uses that schema string to deserialize.

2021-06-07 23:32 UTC, robertcoltheart commented
@AdrianStrugala Please take a look, thanks!

2021-06-08 05:22 UTC, AdrianStrugala commented
Hello,
Thank you for the pull request. I am currently out of office and I don't have a possibility to run the code.
I'll review the PR in next week.
Thanks, 
Adrian

2021-06-13 17:16 UTC, AdrianStrugala requested changes
please do not remove .nupkg and .snupkg files
+ one more comment in files

2021-06-13 17:16 UTC, AdrianStrugala commented on tests/AvroConvertTests/Headless/HeadlessComponentTests.cs
> +            SimpleClass toSerialize = _fixture.Create<SimpleClass>();
please use in the test BaseTestClass and ReducedBaseTestClass - do not create new.

2021-06-14 00:53 UTC, robertcoltheart commented
Up to you, but its very strange to store .nupkg in a git repo, that's what Nuget is for.

Will make the necessary changes.

2021-06-14 01:13 UTC, closed without merging

2021-06-14 01:15 UTC, robertcoltheart commented
@AdrianStrugala See new pr here: #41, I accidently deleted my fork with this branch.